#! /bin/bash

set -eu

TABLE_NAME="$(jq < cfn-output.json -r '.DynamoTable')"

read -r -d '' items <<EOF || true
{
  "$TABLE_NAME": [
    {
      "PutRequest": {
        "Item": {
          "MysfitId": {
            "S": "4e53920c-505a-4a90-a694-b9300791f0ae"
          },
          "Name": {
            "S": "Evangeline"
          },
          "Species": {
            "S": "Chimera"
          },
          "Description": {
            "S": "Evangeline is the global sophisticate of the mythical world. You’d be hard pressed to find a more seductive, charming, and mysterious companion with a love for neoclassical architecture, and a degree in medieval studies. Don’t let her beauty and brains distract you. While her mane may always be perfectly coifed, her tail is ever-coiled and ready to strike. Careful not to let your guard down, or you may just find yourself spiraling into a dazzling downfall of dizzying dimensions."
          },
          "Age": {
            "N": "43"
          },
          "GoodEvil": {
            "S": "Evil"
          },
          "LawChaos": {
            "S": "Lawful"
          },
          "ThumbImageUri": {
            "S": "https://web.archive.org/web/20220405142134im_/https://www.mythicalmysfits.com/images/chimera_thumb.png"
          },
          "ProfileImageUri": {
            "S": "https://web.archive.org/web/20220405142134im_/https://www.mythicalmysfits.com/images/chimera_hover.png"
          },
          "Likes": {
            "N": "0"
          },
          "Adopted": {
            "BOOL": false
          }
        }
      }
    },
    {
      "PutRequest": {
        "Item": {
          "MysfitId": {
            "S": "2b473002-36f8-4b87-954e-9a377e0ccbec"
          },
          "Name": {
            "S": "Pauly"
          },
          "Species": {
            "S": "Cyclops"
          },
          "Description": {
            "S": "Naturally needy and tyrannically temperamental, Pauly the infant cyclops is searching for a parental figure to call friend. Like raising any precocious tot, there may be occasional tantrums of thunder, lightning, and 100 decibel shrieking. Sooth him with some Mandrake root and you’ll soon wonder why people even bother having human children. Gaze into his precious eye and fall in love with this adorable tyke."
          },
          "Age": {
            "N": "2"
          },
          "GoodEvil": {
            "S": "Neutral"
          },
          "LawChaos": {
            "S": "Lawful"
          },
          "ThumbImageUri": {
            "S": "https://web.archive.org/web/20220405142134im_/https://www.mythicalmysfits.com/images/cyclops_thumb.png"
          },
          "ProfileImageUri": {
            "S": "https://web.archive.org/web/20220405142134im_/https://www.mythicalmysfits.com/images/cyclops_hover.png"
          },
          "Likes": {
            "N": "0"
          },
          "Adopted": {
            "BOOL": false
          }
        }
      }
    },
    {
      "PutRequest": {
        "Item": {
          "MysfitId": {
            "S": "0e37d916-f960-4772-a25a-01b762b5c1bd"
          },
          "Name": {
            "S": "CoCo"
          },
          "Species": {
            "S": "Dragon"
          },
          "Description": {
            "S": "CoCo wears sunglasses at night. His hobbies include dressing up for casual nights out, accumulating debt, and taking his friends on his back for a terrifying ride through the mesosphere after a long night of revelry, where you pick up the bill, of course. For all his swagger, CoCo has a heart of gold. His loyalty knows no bounds, and once bonded, you’ve got a wingman (literally) for life."
          },
          "Age": {
            "N": "501"
          },
          "GoodEvil": {
            "S": "Good"
          },
          "LawChaos": {
            "S": "Chaotic"
          },
          "ThumbImageUri": {
            "S": "https://web.archive.org/web/20220405142134im_/https://www.mythicalmysfits.com/images/dragon_thumb.png"
          },
          "ProfileImageUri": {
            "S": "https://web.archive.org/web/20220405142134im_/https://www.mythicalmysfits.com/images/dragon_hover.png"
          },
          "Likes": {
            "N": "0"
          },
          "Adopted": {
            "BOOL": false
          }
        }
      }
    },
    {
      "PutRequest": {
        "Item": {
          "MysfitId": {
            "S": "da5303ae-5aba-495c-b5d6-eb5c4a66b941"
          },
          "Name": {
            "S": "Gretta"
          },
          "Species": {
            "S": "Gorgon"
          },
          "Description": {
            "S": "Young, fun, and perfectly mischievous, Gorgon is mostly tail. She's currently growing her horns and hoping for wings like those of her high-flying counterparts. In the meantime, she dons an umbrella and waits for gusts of wind to transport her across space-time. She likes to tell jokes in fluent Parseltongue, read the evening news, and shoot fireworks across celestial lines. If you like high-risk, high-reward challenges, Gorgon will be the best pet you never knew you wanted."
          },
          "Age": {
            "N": "31"
          },
          "GoodEvil": {
            "S": "Evil"
          },
          "LawChaos": {
            "S": "Neutral"
          },
          "ThumbImageUri": {
            "S": "https://web.archive.org/web/20220405142134im_/https://www.mythicalmysfits.com/images/gorgon_thumb.png"
          },
          "ProfileImageUri": {
            "S": "https://web.archive.org/web/20220405142134im_/https://www.mythicalmysfits.com/images/gorgon_hover.png"
          },
          "Likes": {
            "N": "0"
          },
          "Adopted": {
            "BOOL": false
          }
        }
      }
    },
    {
      "PutRequest": {
        "Item": {
          "MysfitId": {
            "S": "b41ff031-141e-4a8d-bb56-158a22bea0b3"
          },
          "Name": {
            "S": "Snowflake"
          },
          "Species": {
            "S": "Yeti"
          },
          "Description": {
            "S": "While Snowflake is a snowman, the only abomination is that he hasn’t been adopted yet. Snowflake is curious, playful, and loves to bound around in the snow. He likes winter hikes, hide and go seek, and all things Christmas. He can get a bit agitated when being scolded or having his picture taken and can occasionally cause devastating avalanches, so we don’t recommend him for beginning pet owners. However, with love, care, and a lot of ice, Snowflake will make a wonderful companion."
          },
          "Age": {
            "N": "13"
          },
          "GoodEvil": {
            "S": "Evil"
          },
          "LawChaos": {
            "S": "Neutral"
          },
          "ThumbImageUri": {
            "S": "https://web.archive.org/web/20220405142134im_/https://www.mythicalmysfits.com/images/yeti_thumb.png"
          },
          "ProfileImageUri": {
            "S": "https://web.archive.org/web/20220405142134im_/https://www.mythicalmysfits.com/images/yeti_hover.png"
          },
          "Likes": {
            "N": "0"
          },
          "Adopted": {
            "BOOL": false
          }
        }
      }
    },
    {
      "PutRequest": {
        "Item": {
          "MysfitId": {
            "S": "3f0f196c-4a7b-43af-9e29-6522a715342d"
          },
          "Name": {
            "S": "Gary"
          },
          "Species": {
            "S": "Kraken"
          },
          "Description": {
            "S": "Gary loves to have a good time. His motto? “I just want to dance.” Give Gary a disco ball, a DJ, and a hat that slightly obscures the vision from his top eye, and Gary will dance the year away which, at his age, is like one night in humanoid time. If you're looking for a low-maintenance, high-energy creature companion that never sheds and always shreds, Gary is just the kraken for you."
          },
          "Age": {
            "N": "2709"
          },
          "GoodEvil": {
            "S": "Neutral"
          },
          "LawChaos": {
            "S": "Chaotic"
          },
          "ThumbImageUri": {
            "S": "https://web.archive.org/web/20220405142134im_/https://www.mythicalmysfits.com/images/kraken_thumb.png"
          },
          "ProfileImageUri": {
            "S": "https://web.archive.org/web/20220405142134im_/https://www.mythicalmysfits.com/images/kraken_hover.png"
          },
          "Likes": {
            "N": "0"
          },
          "Adopted": {
            "BOOL": false
          }
        }
      }
    }
  ]
}
EOF

aws dynamodb batch-write-item --request-items "$items"
